[package]
name = "hickory-dns-v6synth"
version = "0.2.0"
edition = "2024"

[features]
default = ["sqlite", "resolver", "tls-ring", "https-ring", "dnssec-ring", "rustls-platform-verifier", "ascii-art"]

# if enabled, the hickory-dns binary will print ascii-art on start, disable to reduce the binary size
ascii-art = []

blocklist = ["hickory-server/blocklist"]
recursor = ["hickory-server/recursor"]
# Recursive Resolution is Experimental!
resolver = ["hickory-server/resolver"]
sqlite = ["hickory-server/sqlite", "dep:rusqlite"]
prometheus-metrics = ["metrics", "dep:http", "dep:hyper", "dep:hyper-util", "dep:metrics-exporter-prometheus", "dep:tokio-util"]
metrics = ["hickory-server/metrics", "dep:metrics", "dep:metrics-process"]

tls-aws-lc-rs = ["hickory-server/tls-aws-lc-rs", "__tls"]
https-aws-lc-rs = ["hickory-server/https-aws-lc-rs", "tls-aws-lc-rs", "__https"]
quic-aws-lc-rs = ["hickory-server/quic-aws-lc-rs", "tls-aws-lc-rs", "__quic"]
h3-aws-lc-rs = ["hickory-server/h3-aws-lc-rs", "quic-aws-lc-rs", "__h3"]

tls-ring = ["hickory-server/tls-ring", "__tls"]
https-ring = ["hickory-server/https-ring", "tls-ring", "__https"]
quic-ring = ["hickory-server/quic-ring", "tls-ring", "__quic"]
h3-ring = ["hickory-server/h3-ring", "quic-ring", "__h3"]

__tls = ["dep:rustls"]
__https = []
__quic = []
__h3 = []

dnssec-aws-lc-rs = ["hickory-server/dnssec-aws-lc-rs", "dep:rustls-pki-types", "__dnssec"]
dnssec-ring = ["hickory-server/dnssec-ring", "dep:rustls-pki-types", "__dnssec"]
__dnssec = []

webpki-roots = ["hickory-server/webpki-roots"]
rustls-platform-verifier = ["hickory-server/rustls-platform-verifier"]

[dependencies]
async-trait = "0.1.43"
cfg-if = "^1.0.0"
# clap features:
# - `suggestions` for advanced help with error in cli
# - `derive` for clap derive api
# - `help` to generate --help
clap = { version = "4.0.0", default-features = false, features = ["cargo", "derive", "help", "std", "suggestions"] }
futures-util = { version = "0.3.5", default-features = false, features = ["std"] }
http = { version = "1.1", optional = true }
hyper = { version = "1.6.0", features = ["server"], optional = true }
hyper-util = { version = "0.1.11", features = ["server-auto", "server-graceful", "tokio"], optional = true }
ipnet = { version = "2.3.0", features = ["serde"] }
# rusqlite is actually only needed for test situations, but we need an optional dependency
# here so we can disable it for MSRV tests (rusqlite only supports latest stable)
rusqlite = { version = "0.35", features = ["bundled", "time"], optional = true }
socket2 = "0.5"
rustls = { version = "0.23.23", optional = true }
rustls-pki-types = { version = "1.10", optional = true }
serde = { version = "1.0", features = ["derive"] }
time = "0.3"
tracing = "0.1.30"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "std"] }
tokio = { version = "1.21", features = ["time", "rt", "signal"] }
tokio-util = { version = "0.7.9", optional = true }
toml = "0.8.14"
hickory-client = "0.25.2"
hickory-proto = "0.25.2"
hickory-resolver = "0.25.2"
hickory-server = { version = "0.25.2", features = ["toml"] }
metrics = { version = "0.24.1", optional = true }
metrics-exporter-prometheus = { version = "0.16.2", optional = true }
metrics-process = { version = "2.4.0", optional = true }
rhai = { version = "1.17.1", features = ["serde", "sync"] }
ipnetwork = "0.20.0"
async-channel = "2.2.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
futures-executor = { version = "0.3.5", default-features = false, features = ["std"] }
regex = "1.3.4"
hickory-proto = { version = "0.25.2", features = ["testing", "std"] }
hickory-resolver = "0.25.2"
toml = "0.8.14"
webpki-roots = "0.26"
# metrics tests
reqwest = { version = "0.12.12", default-features = false }
prometheus-parse = { version = "0.2.5" }

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
max_combination_size = 2
denylist = ["__tls", "__https", "__quic", "__h3", "__dnssec"]